image: cirrusci/flutter:stable

stages:
  - build
  - analyze
  - test

before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build

  script:
    - flutter build apk
    - flutter build appbundle


unit_test:
  stage: test

  script:
    - flutter test test/*
  

analyze:
  stage: analyze

  script:
    - echo job excluded