image: openjdk:8-jdk

stages:
  - test
  - build

build:apk:
  stage: build
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk

build:bundle:
  stage: build
  script:
    - flutter build appbundle
  artifacts:
    paths:
      - build/app/outputs/bundle

test:flutter:
  stage: test
  script:
    - flutter test
