image: cirrusci/flutter:stable

stages:
  - build
  - linter
  - test

before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build

  script:
    - flutter build apk
    - flutter build appbundle


unit_test:
  stage: test

  script:
    - flutter test test/*
  

linter:
  stage: linter

  script:
    - flutter analyze